- name: start a PostgreSQL Prometheus exporter container
  docker_container:
    name: postgres-exporter
    image: wrouesnel/postgres_exporter
    state: started
    recreate: yes
    restart_policy: always
    read_only: yes
    exposed_ports:
      - 9187
    ports:
      - "{{ posgtres_exporter_host_address }}:9187:9187"
    env:
      DATA_SOURCE_NAME: "user={{ postgres_exporter_postgres_user }} host={{ postgres_exporter_postgres_host }} sslmode=disable port={{ postgres_exporter_postgres_port }}"
