- name: put a DDL script
  template: src=postgres_exporter.sql dest=/root/postgres_exporter.sql

- name: check if objects already exist
  shell: psql "host=127.0.0.1 port=5433 user=postgres dbname=postgres sslmode=disable password=MaeTieghujoow1ohReeb" -tAc "SELECT 1 FROM pg_roles WHERE rolname='postgres_exporter'" | grep -q 1
  register: result
  changed_when: false
  ignore_errors: true

- name: run the DDL script
  command: psql "host=127.0.0.1 port={{ haproxy_patroni_frontend_port }} user=postgres dbname=postgres sslmode=disable password={{ patroni_postgres_password }}" -f /root/postgres_exporter.sql
  when: result.rc != 0
  run_once: True

- name: start a PostgreSQL Prometheus exporter container
  docker_container:
    name: postgres-exporter
    image: wrouesnel/postgres_exporter
    state: started
    recreate: yes
    restart_policy: always
    read_only: yes
    exposed_ports:
      - 9187
    ports:
      - "{{ posgtres_exporter_host_address }}:9187:9187"
    env:
      DATA_SOURCE_NAME: "user={{ postgres_exporter_postgres_user }} password={{ postgres_exporter_postgres_password }} host={{ postgres_exporter_postgres_host }} sslmode=disable port={{ postgres_exporter_postgres_port }} dbname=postgres"
